### ISSUE TITLE
error when specifying columns to be selected

### ISSUE THREAD

**Issue by jamesdixon** [anyong/bookshelf-page#1]
Hi,

First off, great work on this plugin!

I'm attempting to use it with a plugin that I'm building to parse parameters specified in JSON API and am running into an error. The error occurs when I attempt to specify the columns to be selected on a query. Example:

I have a `customer` model that has a `key_code` field. Say that I only want to select that field -- to enable that, I'm using `.column()` to specify which columns to return. My code would look something like:

``` javascript
var model = this.constructor.forge();
  return model.query((qb) => {
    qb.column.apply(qb, ['key_code']);
})
.fetchPage({limit: 10, offset: 0});
```

When doing something like that, I receive the following error:

`Error: Uncaught error: error: select "key_code", "id", count(distinct "customer"."id") from "customer" - column "customer.key_code" must appear in the GROUP BY clause or be used in an aggregate function`

It appears that the columns I specified in my query are being passed into the `count()` function in your code.

Any thoughts on resolving this?

Thanks!
James

**Comment by anyong** [comment]
Definitely a bug. I see where the issue is, give me a minute I'll see if I can fix it easily.

**Comment by anyong** [comment]
@jamesdixon Please update via npm to v0.3.1 and make sure this is fixed.

**Comment by jamesdixon** [comment]
@anyong works like a charm! Thanks for the quick fix :+1:
