### ISSUE TITLE
issue on node 0.10/0.12

### ISSUE THREAD

**Issue by jamesdixon** [anyong/bookshelf-page#2]
Hi again,

I found an issue when using the library on Node 0.10 and 0.12. It appears that Babel isn't polyfilling `string.startsWith()`, which is causing errors. There are two options: either use a polyfill or just switch to `indexOf()`. The latter seems simpler. 

I'll submit a PR -- if you'd like to go another route, that's fine too!

Best,
James

**Comment by jamesdixon** [comment]
By the way, specifically, the errors are thrown in the `orderBy` method.

**Comment by anyong** [comment]
Ah yeah I'm aware of the startsWith polyfill not working. I fixed it on the
PR from this package to bookshelf but I guess I forgot to pull those
changes here. PR would be great, thanks.

**Comment by jamesdixon** [comment]
@anyong thanks! will you be publishing to npm soon?

**Comment by anyong** [comment]
@jamesdixon I published as soon as you made the PR earlier...

**Comment by jamesdixon** [comment]
Got it. Sorry, for some reason it wasn't showing immediately
